#!/bin/bash

###
### This very basic script is responsible for sending emails whose content
### has already been generated by 'scrpae.sh'
###

CCs="ppannuto@umich.edu gpulkit@umich.edu brehob@umich.edu"
TAG="[470 W12 SVN]"

for file in `ls mails`; do
	echo "$file"
	mail -s "$TAG Project 3 SVN status" $file $CCs < mails/$file
done
